/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElPopconfirm: typeof import('element-plus/es')['ElPopconfirm']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    FixedHeader: typeof import('./src/components/FixedHeader.vue')['default']
    GoodsItem: typeof import('./src/components/GoodsItem.vue')['default']
    HomeBanner: typeof import('./src/components/home/HomeBanner.vue')['default']
    HomeCategory: typeof import('./src/components/home/HomeCategory.vue')['default']
    HomeHot: typeof import('./src/components/home/HomeHot.vue')['default']
    HomeNew: typeof import('./src/components/home/HomeNew.vue')['default']
    HomePanel: typeof import('./src/components/home/HomePanel.vue')['default']
    HomeProduct: typeof import('./src/components/home/HomeProduct.vue')['default']
    LayoutFooter: typeof import('./src/components/layout/LayoutFooter.vue')['default']
    LayoutHeader: typeof import('./src/components/layout/LayoutHeader.vue')['default']
    LayoutNav: typeof import('./src/components/layout/LayoutNav.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
  export interface ComponentCustomProperties {
    vInfiniteScroll: typeof import('element-plus/es')['ElInfiniteScroll']
  }
}
